---
title: "map covid relevant indicators"
author: "GIS Data Unit"
date: "3/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tmap)
library(dplyr)
library(butteR)
library(sf)
library(lubridate)
tmap_mode("view")

kobo_coords<-c("X_gps_reading_longitude",
               "X_gps_reading_latitude")


cmp_gdb<- "../../../../01_GIS_BASE_Data/01_boundaries/03_camp"
cmp<- st_read(cmp_gdb,"CampBoundaryA1_190310")

wash_r3_cont<-read.csv("../../../01_WASH/02_70_DNW_UNICEF_2019/03_WASH_HH_R3/89_rscript/WASH_HH_R3_2019/inputs/WASH_HH_R3/clean_data/Container_19June2019.csv",
                       stringsAsFactors = FALSE,
                       row.names = NULL, na.strings = c(""," ",NA, "NA"),
                       strip.white = TRUE)

wash_r3_indiv<-read.csv("../../../01_WASH/02_70_DNW_UNICEF_2019/03_WASH_HH_R3/89_rscript/WASH_HH_R3_2019/inputs/WASH_HH_R3/clean_data/Individual_19June2019.csv",
                        stringsAsFactors = FALSE,
                        row.names = NULL, na.strings = c(""," ",NA, "NA"),
                        strip.white = TRUE)
wash_r3_hh_raw<-read.csv("../../../01_WASH/02_70_DNW_UNICEF_2019/03_WASH_HH_R3/02_data_collection/clean_data/Header_07july2019.csv",
                     stringsAsFactors = FALSE,
                     row.names = NULL, na.strings = c(""," ",NA, "NA"),
                     strip.white = TRUE)

wash_r3_hh_clean<-read.csv("../../../01_WASH/02_70_DNW_UNICEF_2019/03_WASH_HH_R3/89_rscript/WASH_HH_R3_2019/inputs/WASH_HH_R3/clean_data/Header_07july2019.csv",
                        stringsAsFactors = FALSE,
                        row.names = NULL, na.strings = c(""," ",NA, "NA"),
                        strip.white = TRUE)

wash_r3_hh_clean<- wash_r3_hh_clean %>% left_join(wash_r3_hh_raw %>%
                                 select(X_uuid,kobo_coords))
source("../../../01_WASH/02_70_DNW_UNICEF_2019/03_WASH_HH_R3/89_rscript/WASH_HH_R3_2019/functions/wash_hh_r3_2019_recoding.R")
source("../../../01_WASH/02_70_DNW_UNICEF_2019/03_WASH_HH_R3/89_rscript/WASH_HH_R3_2019/functions/wash_container_volume_bgd_2019.R")



wash<-wash_hh_r3_2019_recoding(hh_data = wash_r3_hh_clean,
                         container_data = wash_r3_cont,
                         individual_data = wash_r3_indiv)
whh<-wash$HH_dataset
wash_indicators<-c("lat_soap",
                   "wst_disp",
                   "soap_yest",
                   "soap_yest_when",
                   "wash_hands",
                   "hnd_sp",
                   "IS.disab")

whh_sf<-st_as_sf(whh,coords = kobo_coords, crs=4326)

map_bare<-tm_basemap(NULL)+
  tm_shape(cmp)+
  tm_polygons()+
  tm_text("New_Camp_N")+
  tm_shape(whh_sf)

```

## Mapping Point Data

```{r}
map_bare+tm_dots(wash_indicators[1]) 

```


```{r cars}

for(i in 1: length(wash_indicators)){
 map_bare+tm_dots(wash_indicators[i]) 
}

  
  

```

